version: "3.7"

services:
  dm_forwarder:
    container_name: dm_forwarder
    image: ts-dockerhub.lsst.org/lsstts/dm_forwarder:dm_forwarder
    user: ${IIP_UID}:${IIP_GID}
    build:
      context: ./
      args:
        - cmakeURL=https://github.com/Kitware/CMake/releases/download/v3.15.4/cmake-3.15.4-Linux-x86_64.sh
        - bbcpURL=https://www.slac.stanford.edu/~abh/bbcp/bbcp.git/
        - rabbitmqcURL=http://lsst-web.ncsa.illinois.edu/~srp/packages/rabbitmq-c/v0.10.0.tar.gz
        - SimpleAmqpClientURL=http://lsst-web.ncsa.illinois.edu/~srp/packages/SimpleAmqpClient/SimpleAmqpClient-2.4.0.tar.gz
        - yamlcppURL=http://lsst-web.ncsa.illinois.edu/~srp/packages/yaml-cpp/yaml-cpp-0.6.3.tar.gz
        - cfitsioURL=http://lsst-web.ncsa.illinois.edu/~srp/packages/cfitsio/cfitsio-3.450.tar.gz
        - daqURL=http://lsst-web.ncsa.illinois.edu/~srp/packages/daq/R4-V4.11_ds100.tgz
    volumes:
      - /var/tmp/data:/var/tmp/data
      - /var/log/iip:/var/log/iip
      - /home/iip:/home/iip
      - /etc/passwd:/etc/passwd
      - /etc/group:/etc/group
      - /tmp/:/tmp
    environment:
      - USER=iip
      - HOME=/home/iip
      - KRB5CCNAME=${KRB5CCNAME_FILE}
    network_mode: host
    pid: host
    tty: true
