version: "3.8"

services:
  dm_forwarder:
    container_name: dm_forwarder
    image: lsstts/dm_forwarder:${DM_FORWARDER_VERSION}
    build:
      context: ./
      args:
        - cmakeURL=https://github.com/Kitware/CMake/releases/download/v3.15.4/cmake-3.15.4-Linux-x86_64.sh
        - bbcpURL=https://www.slac.stanford.edu/~abh/bbcp/bbcp.git/
        - rabbitmqcURL=http://lsst-web.ncsa.illinois.edu/~hwin16/packages/rabbitmq-c/v0.10.0.tar.gz
        - SimpleAmqpClientURL=http://lsst-web.ncsa.illinois.edu/~hwin16/packages/SimpleAmqpClient/SimpleAmqpClient-2.4.0.tar.gz
        - yamlcppURL=http://lsst-web.ncsa.illinois.edu/~hwin16/packages/yaml-cpp/yaml-cpp-0.6.3.tar.gz
        - cfitsioURL=http://lsst-web.ncsa.illinois.edu/~hwin16/packages/cfitsio/cfitsio-3.450.tar.gz
        - daqURL=http://lsst-web.ncsa.illinois.edu/~hwin16/packages/daq/R4-V2.3.tgz
    volumes:
      - dm_forwarder_vol:/var/tmp/data
      - dm_forwarder_vol:/var/log/iip
      - ./etc/environment/.lsst:/root/.lsst
      - ./etc/environment/config:/opt/lsst/dm_forwarder/config
    networks:
      dm_forwarder_net: {}
    tty: true

  redis:
    image: redis
    container_name: redis
    hostname: my-redis
    ports:
      - "6379:6379"
    networks:
      dm_forwarder_net: {}

  rabbitmq:
    build:
      context: ./etc/docker/rabbitmq
    container_name: rabbitmq
    hostname: my-rabbit
    ports:
      - "5672:5672"
    networks:
      dm_forwarder_net: {}

  test:
    image: lsstts/dm_forwarder_test:${DM_FORWARDER_VERSION}
    build:
      context: ./etc/docker/tests
      args:
        - DM_FORWARDER_VERSION=${DM_FORWARDER_VERSION}
    environment:
      LD_LIBRARY_PATH: /app/lib
    volumes:
      - dm_forwarder_vol:/var/tmp/data
      - dm_forwarder_vol:/var/log/iip
      - ./etc/environment/.lsst:/root/.lsst
      - ./etc/environment/config:/opt/lsst/dm_forwarder/config
    depends_on:
      - redis
      - rabbitmq
    networks:
      dm_forwarder_net: {}

volumes:
  dm_forwarder_vol:

networks:
  dm_forwarder_net:
